alias downup='sudo ifdown wlan0 && sudo ifup wlan0'
alias image='display-im6'
alias efm='enlightenment_filemanager'
alias bogartz='/home/will/Documents/Teaching/UMass/PSYC\ 240/Bogartz'
alias 640='/home/will/Documents/Teaching/UMass/PSYC\ 640/'
alias gs='git status'
alias ga='git add'
